
CFLAGS = -Wall -Werror -g -O0

get_variable_data_type_generic: get_variable_data_type_generic.c
	gcc $(CFLAGS) get_variable_data_type_generic.c -o get_variable_data_type_generic

clean:
	rm -f get_variable_data_type_generic

