
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

object_struct_reference_copy: object_struct_reference_copy.c
	gcc $(CFLAGS) object_struct_reference_copy.c -o object_struct_reference_copy

clean:
	rm -f object_struct_reference_copy

