
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

occupie_ram: occupie_ram.c
	gcc $(CFLAGS) occupie_ram.c -o occupie_ram

clean:
	rm -f occupie_ram

