
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

dynamic_growing_array_with_structs: dynamic_growing_array_with_structs.c
	gcc $(CFLAGS) dynamic_growing_array_with_structs.c -o dynamic_growing_array_with_structs

clean:
	rm -f dynamic_growing_array_with_structs

