
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

sound_openal_example: sound_openal_example.c
	gcc $(CFLAGS) sound_openal_example.c -o sound_openal_example

clean:
	rm -f sound_openal_example

