
CFLAGS = -Wall -Werror -g -O0

final_sample_gnu_compiler: final_sample_gnu_compiler.c
	gcc $(CFLAGS) final_sample_gnu_compiler.c -o final_sample_gnu_compiler

clean:
	rm -f final_sample_gnu_compiler

