
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

thread_counter_example: thread_counter_example.c
	gcc $(CFLAGS) thread_counter_example.c -o thread_counter_example

clean:
	rm -f thread_counter_example

