
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

struct_pointer: struct_pointer.c
	gcc $(CFLAGS) struct_pointer.c -o struct_pointer

clean:
	rm -f struct_pointer

