
CFLAGS = -pthread -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0 

thread_example: thread_example.c
	gcc $(CFLAGS) thread_example.c -o thread_example

clean:
	rm -f thread_example

