
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

array_of_integers: array_of_integers.c
	gcc $(CFLAGS) array_of_integers.c -o array_of_integers

clean:
	rm -f array_of_integers

