
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

string_array_lesson: string_array_lesson.c
	gcc $(CFLAGS) string_array_lesson.c -o string_array_lesson

clean:
	rm -f string_array_lesson

