
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

array_of_structs: array_of_structs.c
	gcc $(CFLAGS) array_of_structs.c -o array_of_structs

clean:
	rm -f array_of_structs

