
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

monitor_ethernet: monitor_ethernet.c
	gcc $(CFLAGS) monitor_ethernet.c -o monitor_ethernet

clean:
	rm -f monitor_ethernet

