
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

preprocessor_lesson: preprocessor_lesson.c
	gcc $(CFLAGS) preprocessor_lesson.c -o preprocessor_lesson

clean:
	rm -f preprocessor_lesson

