
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

discord_help: discord_help.c
	gcc $(CFLAGS) discord_help.c -o discord_help

clean:
	rm -f discord_help

