
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

simple_game_engine: simple_game_engine.cpp
	# gcc $(CFLAGS) simple_game_engine.cpp -o simple_game_engine
	g++ -o simple_game_engine simple_game_engine.cpp -lcurses

clean:
	rm -f simple_game_engine

