
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

shader_not_working: shader_not_working.c
	gcc $(CFLAGS) shader_not_working.c -lm -o shader_not_working

clean:
	rm -f shader_not_working

