
CFLAGS = -Wall -Werror -g -O0

opal_config_bottom_lesson: opal_config_bottom_lesson.c
	gcc $(CFLAGS) opal_config_bottom_lesson.c -o opal_config_bottom_lesson

clean:
	rm -f opal_config_bottom_lesson

