
CFLAGS = -Wall -Werror -g -O0

return_string_from_function: return_string_from_function.c
	gcc $(CFLAGS) return_string_from_function.c -o return_string_from_function

clean:
	rm -f return_string_from_function

