
CFLAGS = -Wall  -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

dynamic_array_preprocessor: dynamic_array_preprocessor.c
	gcc $(CFLAGS) dynamic_array_preprocessor.c -o dynamic_array_preprocessor

clean:
	rm -f dynamic_array_preprocessor

