
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

dynamic_growing_array: dynamic_growing_array.c
	gcc $(CFLAGS) dynamic_growing_array.c -o dynamic_growing_array

clean:
	rm -f dynamic_growing_array

