
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

simple_array: simple_array.c
	gcc $(CFLAGS) simple_array.c -o simple_array

clean:
	rm -f simple_array

