
CFLAGS =  -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

logical_operators: logical_operators.c
	gcc $(CFLAGS) logical_operators.c -o logical_operators

clean:
	rm -f logical_operators

