
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

algorhitms_search: algorhitms_search.c
	gcc $(CFLAGS) algorhitms_search.c -o algorhitms_search

clean:
	rm -f algorhitms_search

