// A_RAM = array of random access memory
// c file 
#include <stdio.h>
#include <stdlib.h>
void f_other_scope(
   int * n_int_address // datatype * varname => the variable will hold an address/index !!!!!
   ){

   // so now we can change the value here aswell
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   // *n_int_address = 11235 == A_RAM[n_int_address] = 11235
   *n_int_address = 11235; 

   printf("n_int %i\n", *n_int_address);

}
int main() {
   printf("main called");

   // int * n_int = 10; // we cannot assign data to a pointer

   // int * n_int;
   // n_int = 10; // we cannot assign data to a pointer

   int * n_int_address;
   // the variable n_int can only hold an adress 
   n_int_address = malloc(1);
   printf("address n_int:%p\n", n_int_address);


   // now if we dont use the * , the variable will automatically get an adress
   int n_int_value;
   // but to read out the adress of the variable we need to prefix the variable with & (ampersand)
   printf("address n_int_value:%p\n", &n_int_value);
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)
   // &n_int_value == A_RAM.indexOf(n_int_value)


   //now to set the value of the address/pointer
   // n_int_address = 1234 // this would set the address itself
   // * in front of variable but not at initialization !!!
   // means , dereferencing == memory[n_int_adress], getting the value of the 
   // address
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   // *n_int_address == A_RAM[n_int_address]
   *n_int_address = 1234;

   // so to change a normal int variable in a different scope 
   // we need to pass the address of it to the scope
   f_other_scope(&n_int_value);

   printf("main scope\n");
   printf("n_int %i\n", n_int_value);
   
   return 0;
}
