
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

int_pointer: int_pointer.c
	gcc $(CFLAGS) int_pointer.c -o int_pointer

clean:
	rm -f int_pointer

