
CFLAGS = -Wall -Werror -g -O0

final_sample_coding_on_paper: final_sample_coding_on_paper.c
	gcc $(CFLAGS) final_sample_coding_on_paper.c -o final_sample_coding_on_paper

clean:
	rm -f final_sample_coding_on_paper

