
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

thread_multiple: thread_multiple.c
	gcc $(CFLAGS) thread_multiple.c -o thread_multiple

clean:
	rm -f thread_multiple

