
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

memory_management_unit: memory_management_unit.c
	gcc $(CFLAGS) memory_management_unit.c -o memory_management_unit

clean:
	rm -f memory_management_unit

