
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

c_read_keyboard_input: c_read_keyboard_input.c
	gcc $(CFLAGS) c_read_keyboard_input.c -o c_read_keyboard_input

clean:
	rm -f c_read_keyboard_input

