
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

change_address_of_pointer: change_address_of_pointer.c
	gcc $(CFLAGS) change_address_of_pointer.c -o change_address_of_pointer

clean:
	rm -f change_address_of_pointer

