
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

number_of_cpu_cores: number_of_cpu_cores.c
	gcc $(CFLAGS) number_of_cpu_cores.c -o number_of_cpu_cores

clean:
	rm -f number_of_cpu_cores

