
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

memory_allocaiont_lession: memory_allocaiont_lession.c
	gcc $(CFLAGS) memory_allocaiont_lession.c -o memory_allocaiont_lession

clean:
	rm -f memory_allocaiont_lession

