
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

send_raw_ethernet_frame: send_raw_ethernet_frame.c
	gcc $(CFLAGS) send_raw_ethernet_frame.c -o send_raw_ethernet_frame

clean:
	rm -f send_raw_ethernet_frame

