
CFLAGS = -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O0

huffman_encoding: huffman_encoding.c
	gcc $(CFLAGS) huffman_encoding.c -o huffman_encoding

clean:
	rm -f huffman_encoding

